telosnetwork/open-block-explorer

.eslintrc.js, .prettierrc
Resolve Prettier error of 'cr' that appeared when running on a windows machine.
Saw errors on pulling OBE, updating eslint for auto handling line endings.
=> Remove prettier\prettier Delete 'CR' Error

netlify.toml
use alternate endpoint for testnet, missing data produces error on fetching account creator
=> fix: replace hyperion endpoint for testnet

src/api/hyperion.ts, src/api/index.ts, src/components/Header.vue, src/components/ProposalTable.vue, src/composables/useAuthenticator.ts, src/css/app.sass, src/pages/Proposal.vue, src/types/Actions.ts, src/types/PaginationSettings.ts, src/types/Producers.ts, src/types/Proposal.ts, src/types/index.ts
This PR creates a page in the `proposal` route. This page will show any user all the multi-signature proposals in the network. These proposals can be filtered by the Block Producer which signature is needed. 
For logged in users, the page also contains the `my proposals` tab which contains two lists: the first one is the proposals that need to be signed or have already been signed by the user, the second is the proposals that the user has created.
Fixes # 161
The scoping of white color for `q-select__dropdown-icon` [here](https://github.com/telosnetwork/open-block-explorer/compare/develop...161-msig-proposals#diff-87f65ea85740352e3eb5d7734f51f3fabd8f77b96a013e4a550b1399972606bdR41) was due to the impact it had in the overall select element. We moved so only the search component has its …
=> [ #161 ]  Proposal page shows all multi-signature proposals

src/components/ProposalAuthorization.vue
Includes account autocomplete for creating a msig. It finds the account and list the permissions. If there are other accounts in the permission, it also lists them.
Fixes #249
=> feat: component to search account and autocomplete permissions

src/store/account/actions.ts, src/store/account/mutations.ts, src/store/account/state.ts
Fixed the amount of REX to unstake value. It was giving the tlos amount and not the correct rex amount
Fixes #265 
* Hardware:
* Toolchain:
* SDK:
=> 265 bug unlend rex fails due to using tlos amount as rex amount

src/api/hyperion.ts, src/api/index.ts, src/components/ProposalTable.vue, src/pages/ProposalItem.vue, src/types/Proposal.ts
- Label `Active BP` beside each active BP
- Lists the number of active BPs approvals right next to the overall number
- Approvals are listed:
- Active BPs that have approved 
- Active BP's that **haven't** approved
- Standby BPs + accounts that have approved
- Standby BPs + accounts that **haven't** approved
- Removes executed/not executed from the `/proposals` table. The filter indicates if a proposal has reached a final state or not. A cancelled proposal would be marked as executed, so to avoid misleading information, we removed the column. To add the cancelled information to the list, we would need to make additional requests and the current filter is sufficient to show the active proposals and the ones that are not anymore.
- Increases to 20 items per page by default for proposals
- …
=> Showing better BP msig information

src/components/Staking/SavingsTab.vue, src/store/account/actions.ts
Savings validation used the wrong value. Saving maturing and matured account values issue fixed.
Maturing rex value shows even though the date has expired. Added some date checks.
- An expired date value now gets added to total matured.
- A date difference greater that a year will now be seen as the account savings value.
- Everything else will be maturing rex.
* Hardware:
* Toolchain:
* SDK:
=> Rex savings fixes

src/components/AccountCard.vue, src/components/Resources/ResourcesInfo.vue, src/components/Staking/StakingDialog.vue, src/components/validators/ValidatorData.vue
Fixed multiple issues.
- Voting TLOS now uses last_stake value instead of last_vote_weight
- Exclude delegated resources from account total
- refresh balance when done doing withdraw rexfund
- issue with null value self delegated resources fixed
=> 379 bug voting tlos amount incorrect

src/boot/ual.ts, src/store/account/actions.ts
Sign transactions with the correct permission instead of defaulting to 'active'.
=> fix: sign the transaction with correct permission

src/components/HeaderSearch.vue
- search for 'stlos' (should see an account and a proposal with same name listed)
- clicking the result under account should redirect to /account page
- clicking the result under 'Proposals' should redirect to the /proposal page
- enter 'stlos' and click 'Enter', should default to account page
- enter 'EOS54X5EiXQRn6gtGhR5vHMRyvZyBtvxV1MsqAdY1nRhc3sUpAjLG' in search bar and click 'Enter', should redirect to /key page
- enter '887ba18e5e9713900885df64da27e52e98deebf7d2c93de4421759f29c57b991' in search bar and click 'Enter', should redirect to /transaction page
- clear search input, click 'Enter', should do nothing
- enter gibberish >13 characters and <53 characters, should show 'no results found' in dropdown and not redirect
-   [x] I …
=> Fix search result selection redirect

src/components/HeaderSearch.vue
added regex to remove trailing and leading spaces and periods from input used for query. filters results based on original input
- search `rng.`, see `rng.oracle` result (previously generated error/no results)
=> fix: regex to ignore trailing and leading spaces and periods

src/components/contract/ContractTables.vue
On the contract table pressing enter will now refresh the table on all filters.
=> fix: enter triggers search on contract table

src/components/Transaction/AccountFormat.vue
Fixed block number not showing on transaction card.
=> fix: block num not showing

src/components/TokensPanel.vue
It is desirable to be able to filter the tokens shown on the account page as requested in #395. 
In order to do that, the URL parameters were used to filter the list of tokens displayed. If the URL parameters are used, only the tokens matching the parameters will be shown. Otherwise, all account tokens are displayed.
=> on the account page the ability to filter tokens

src/components/AccountCard.vue
indeed, there were two different solutions calculating the same REX balance (one was badly implemented) and they were running always in parallel (but not always they end the same way). When the bad implementation ended first, it was overwritten with the good one and vice-versa. So, the final result was always unpredictable.
The bad solutions were removed and the good implementation now is launched always at the end, so it writes the good result.
Note: this is a quick patch to solve the inconsistency bug, but this code needs a big refactoring.
Refreshing several times and checking the total balances is always the same.
-   [x] I have cleaned up the code in the …
=> repairing the REX balance calculation

src/components/TransactionsTable.vue
Date dropdown  filter for transactiontable closes when losing focus.
=> fix: remove persistent date dropdown

src/api/eosio_core.ts, src/api/hyperion.ts, src/api/index.ts, src/components/AccountCard.vue, src/components/KeyAccountsCard.vue, src/components/Resources/BuyRam.vue, src/pages/Key.vue, src/types/Api.ts
- visit account, select keys tab, click key to navigate to accounts keys page
- should display, toggle, and copy as usual
=> 447 should use nodeos for getting key accounts

src/components/AccountCard.vue, src/components/Resources/StakeTab.vue, src/types/StakeResourcesTransactionData.ts, src/types/index.ts
- stake to a single resource (cpu or net) while leaving other as 0.
=> 488 allow staking to single resource

src/components/Resources/BuyRam.vue, src/components/Resources/StakeTab.vue, src/store/account/actions.ts
1. connect account
2. navigate to resources dialog from wallet view
3. click 'buy ram' tab
4. enter a different account for receiver
5. confirm the different account in Anchor as receiver
=> 522 buy ram for different account

src/pages/ProposalItem.vue
Removing Transaction History from Proposal page since it's not accurate in the most of the times.
Currently we are displaying the transactions that we receive from get_block call, this call can include some transactions that aren't related to the proposal that is being consulted.
Not removing the get_block call since the returned information it's being used in more places.
- Opened a Proposal and checked if the Transaction History is being displayed.
=> Fixes #493: Removing transaction history from ProposalItem

src/pages/ProposalItem.vue, src/utils/sleep.ts
Moved the code from onMounted inside of ProposalItem to a new function that will load the proposal and update the fields, called this new function after signTransition to reload the information. Since we cannot call the new function right after the sign transaction due the chain delay, created a new util function called "sleep" that will wait for one second before reload the UI information. 
Manually tested the code on the following scenarios:
- Created a proposal and approve it;
- Unapproved a proposal that was approved;
- Canceled a proposal;
- Executed a proposal;
In all scenarios the UI were successfully refreshed.
-   [X] …
=> Fixes 436: Automatically refresh proposal changes when they're updated

src/components/Resources/BuyRam.vue, src/components/Resources/RefundTab.vue, src/components/Resources/SellRam.vue, src/components/Resources/StakeTab.vue, src/components/Resources/UnstakeTab.vue
This PR fixes an issue where an empty error pops up when copying cleos commands in the account view. The error was due to the application attempting to submit a transaction when, for cleos users, the user is expected to run the command outside of OBE. The fix is to add a simple check before opening a transaction.
- go to https://deploy-preview-559--obe-staging.netlify.app/
- login using a cleos account such as `montevideouy` with permission `active`
- go to the account page, eg. `https://deploy-preview-559--obe-staging.netlify.app/account/montevideouy`
- click **resources** button
- do the following steps for each of the tabs "Add CPU/NET", "Remove CPU/NET", "Refund CPU/NET", "Buy RAM", "Sell RAM"
- fill out all fields with any data, e.g. `1 TLOS`
- click `Confirm`
- in the modal that …
=> #526 | Cleos error fix

src/components/Resources/BuyRam.vue
Currently bytes are displayed as having precision greater than whole numbers, but bytes should be displayed as integers with no decimals in this case. 
- sign into an account, e.g. using cleos `eztestnet123`
- go to the account page for your account, e.g. /account/eztestnet123
- click `Resources` button
- go to `Buy RAM` tab
- enter any amount into the `Amount of RAM to buy in TLOS` field
- the amount of bytes displayed below the input should be an integer rather than a floating point number
-   [x] Any dependent changes have been merged and published in …
=> #539 | Fix bytes display

src/components/TransactionsTable.vue
This PR removes the expandable / collapsible row for actions in the same transaction in the account view. instead all actions are given their own line to match industry standard 
**note:** testing must be completed locally
- change line of 6 `.env` file from `CHAIN_NAME=telos-testnet` to `CHAIN_NAME=telos` (this switches to mainnet)
- run `yarn dev`
- go to http://localhost:8080/account/treasury.tcd
- scroll to bottom of page, change records per page to 200, await loading complete
- note that there are 11 transactions with ID `a54fba13`
- compare to the same view here, where the same 11 transfers are nested: https://explorer.telos.net/account/treasury.tcd
- …
=> #487 | Remove nesting from transaction table

src/components/Resources/StakeTab.vue, src/components/Resources/UnstakeTab.vue
- validates transaction inputs for unstake rex and cpu to allow unstaking single resource 
- disables cleos or Anchor transactions if invalid inputs
- if cpu and net both left as zero, it should notify prompt the user for input value 
- input non-zero value for cpu, click 'confirm' while logged in via cleos, should display '0.0000 TLOS' for the empty input in the generated cleos command (instead of 'NaN TLOS'), test for net only input as well.  
-   [ ] I have checked my …
=> 550 cleos command with nan telos

src/api/fuel.ts
The fuel service is working as expected in the chains that are supported but is introducing problems in the not supported ones. For that, I push this little snippet patch to solve the problem. All the information was always available but never used to discard unsupported chains.
- Login to testnet
- open the browser inspector and enter tab Network
- modify filters, select: Fetch/XHR
- try to sign any transaction (send tokens, stake or unstake)
- You should not see a POST request like this: https://telos.greymass.com/v1/resource_provider/request_transaction
- You should be able to perform the signing as regularly (without fuel)
-   [x] I have commented my code
-   [x] I have checked my code …
=> removing fuel when not supported

src/components/Staking/SavingsTab.vue, src/components/Staking/StakeFromResources.vue, src/components/Staking/StakingTab.vue, src/components/Staking/UnstakingTab.vue
This PR is a followup to #559 where I missed some examples of this error. It fixes an issue where an empty error pops up when copying cleos commands in the account view. The error was due to the application attempting to submit a transaction when, for cleos users, the user is expected to run the command outside of OBE. The fix is to add a simple check before opening a transaction.
- go to https://deploy-preview-562--obe-staging.netlify.app/
- login using a cleos account such as `eztestnet123` with permission `active`
- go to the account page, eg. https://deploy-preview-562--obe-staging.netlify.app/account/eztestnet123
- click **Staking (REX)** button
- do the following steps for each of the tabs "Stake", "Unstake", "Stake from CPU/NET", "Savings"
- fill out all fields with any data, e.g. …
=> #526 | Fix cleos errors on staking views

jest.config.js, src/boot/ual.ts, src/components/HeaderSearch.vue, src/components/Resources/UnstakeTab.vue, src/components/Staking/StakingDialog.vue, src/utils/stringValidator.ts, test/jest/__tests__/utils/stringValidator.spec.ts
- resolves bug where user can input invalid account name when signing in with cleos
- updates regexp for account and transaction hex validation
cleos login:
1. click 'connect' and select cleos
2. see updated description in input label
3. attempt to put in invalid character, see 'ok' disabled
4. correct invalid chars, see 'ok' enabled, and continue with login
transaction hex validation:
- in search bar, verify transaction search still works as expected
-   [x] I have …
=> 578 account input validation when signing in w/cleos

src/components/AccountCard.vue
The balance breakdown was not showing all the components of the total balance. This PR changes that, introducing all and each of the different peaces of the total balance.
- go to any account page
- scroll to see the Total Balance and the breakdown
- you should see the following list of balances
- LIQUID (Telos native)
- REX staked (includes savings)
- REX profits
- REX liquid deposits
- STAKED for CPU
- STAKED for NET
- REFUNDING from staking
- DELEGATED by others
- It all (except for DELEGATED) should sum TOTAL
-   [x] Any dependent changes have been …
=> Complete balance breakdown

src/components/Staking/SavingsTab.vue
1. login and navigate to staking(rex) dialog -> savings tab
2. if not maturing amount, go to stake tab and stake to have a 'maturing' balance
3. full value in the top right of the 'move to savings' input should be the sum of matured and _maturing_
4. input validation for exceed amount should allow inputs up to this sum value
5. tooltip should include a note about maturing funds being moved first.
-   [x] I have …
=> 421 staking to savings moves funds from maturing but shows matured as available amount

src/components/WalletModal.vue, src/css/app.sass
The login modal was too big for a small resolution. This PR adapts the style of the involved components to make it more responsive.
- Open the site on a mobile device or use the Desktop browser, open the inspector, and toggle to "device toolbar", so you can see the site in small resolution
- The "Attach an account" title should display smaller so the icon
- Select Cleos for login
- The dialog should be displayed in a nice way using no more than the device with 
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/4420760/220381908-aa84c118-0663-4093-b4ac-b5055d0afec4.png"></td>
<td><img src="https://user-images.githubusercontent.com/4420760/220381930-819e7e2f-fe04-4263-826e-9176d63b8c3a.png"></td>
</tr>
</table>
-   [x] …
=> Adapting cleos login dialog to be more responsive

src/components/TransactionsTable.vue, src/components/transaction/DataFormat.vue, src/components/transaction/TraceTree.vue
The "See more" button was breaking the layout when viewing the Trace tab. This PR fixes that.
- Go to this [block page](https://deploy-preview-617--obe-staging.netlify.app/transaction/cbdfa378ab91c8378516fcbfa595726c7b1bd659d0c130786dfb85b852000383?tab=traces) in trace tab
- You should see the action data with a button on top of the lower half of the cell, covering the data with a transparent gradient color.
- The layout should not break (you should not see a big horizontal scroll)
-   [x] Any dependent changes have been merged and published in …
=> fix: see-more button now does not break the layout when viewing action traces.

src/components/TransactionsTable.vue
Pagination seems inconsistent because you can have new transactions in between and the offset moves. To avoid that this PR introduces the concept of a global sequence range that freezes the range in which we are going to paginate.
- Go to the [home page](https://deploy-preview-618--obe-staging.netlify.app/)
- The Live transaction switcher should be on
- Go to page 2
- Live transaction switcher should turn off
- Remember the first and last block numbers on page 2
- Go to page 3 and back to 2
- Check if the first and last block numbers remain the same 
- …
=> freezing live transactions for more consistent pagination.

src/components/SendDialog.vue
This PR changes the behavior of the send token input on the account page. When clicking the max amount, the full amount is filled rather than the full amount minus 0.1.
- go to https://deploy-preview-621--obe-testnet.netlify.app/
- log into `hyogasereiou` using cleos
- go to https://deploy-preview-621--obe-testnet.netlify.app/account/hyogasereiou
- click `Send`
- click the amount shown above the token amount input
- the full amount should populate in the field
-   [ ] I …
=> #616 | Send token bug

src/components/TransactionsTable.vue, src/components/transaction/ActionFormat.vue, src/pages/Account.vue
This PR modifies the behavior of labels in the transfer tables. Previously, the logged-in user would see special 'send' and 'receive' labels next to transfers involving their account. Now, all actions are displayed the same, including transfers; on an account page, if a transfer involves the account whose page you are viewing, the appropriate send/receive label will be shown next to the action.
- go to the home page, https://deploy-preview-619--obe-testnet.netlify.app
- all actions in the transaction table should look the same, including `eosio -> transfer`
- go to an account page, e.g. https://deploy-preview-619--obe-testnet.netlify.app/account/eztestnet123
- the `eosio -> transfer` actions should show a send/receive label next to them 
- go to an account page with non-`eosio` transfers, …
=> #613 | Transfer labels

src/components/transaction/TraceTree.vue
In some cases, an undefined array was causing the traces page to error out. I fixed this using better null handling.
- go to https://deploy-preview-626--obe-testnet.netlify.app/transaction/a8ab88e8a208b5eb9759dd5189c6fca3a994d15ff4dcce0857b126de669d9303?tab=traces
- reload the page a bunch of times
- you should never see a blank page (reloading leads to blank page in production)
-   [x] I have removed any …
=> #625 | Fix traces error

src/components/resources/BuyRam.vue, src/components/resources/ResourcesInfo.vue, src/components/resources/StakeTab.vue
This PR adds in handling for null account balance scenario
- this one needs to be tested locally using main net
- edit `.env` file to say `CHAIN_NAME=telos`
- run `yarn dev`
- go to http://localhost:8080
- log in using cleos as `saorinhamala`
- go to http://localhost:8080/account/saorinhamala
- click Resources
- click the Buy RAM tab
- the tab should load rather than error out
-   [x] I have removed any …
=> #624 | Fix for undefined account balance

src/api/hyperion.ts, src/components/TransactionsTable.vue, src/types/Actions.ts
This PR updates the logic in TransactionTable to get the full number of rows from the API rather than hardcoded amount. this allows the "next" button to be disabled when there are no more results
- go to https://deploy-preview-642--obe-testnet.netlify.app/account/eztestnet123
- go to second page of transactions
- next button should be disabled
-   [ ] I …
=> #601 | Fix pagination buttons

src/components/AccountCard.vue, src/components/SendDialog.vue, src/components/resources/BuyRam.vue, src/components/resources/StakeTab.vue, src/components/resources/UnstakeTab.vue, src/components/staking/StakingTab.vue
This PR does the following:
- fixes a null handling issue
- updates error messaging for the Staking input
- removes click-to-fill-maximum value for resources inputs
- removes reserved 0.1 TLOS where applicable for inputs 
- go to https://deploy-preview-647--obe-testnet.netlify.app/
- sign in using cleos as `eztestnet111` (zero liquid balance account)
- go to https://deploy-preview-647--obe-testnet.netlify.app/account/eztestnet111
- click Resources
- "Add CPU/Net" and "Buy RAM" tabs should no longer have the ability to click the total amount to fill the input
- exit Resources dialog
- sign out and sign in as `eztestnet123` (non-zero liquid balance)
- go to https://deploy-preview-647--obe-testnet.netlify.app/account/eztestnet123
- click Staking (REX)
- attempt to put a negative value into …
=> #628 | Account inputs updates

src/api/fuel.ts, src/components/SendDialog.vue, src/components/resources/StakeTab.vue, src/components/resources/UnstakeTab.vue, src/components/staking/SavingsTab.vue, src/components/staking/StakeFromResources.vue, src/components/staking/StakingInfo.vue, src/store/account/actions.ts, src/store/chain/actions.ts, src/store/resources/actions.ts, src/utils/string-utils.ts, test/jest/__tests__/store/resources/actions.spec.ts, test/jest/__tests__/utils/string-utils.spec.ts
This PR makes it so all balances (except unstake - #662 has been created for this) refresh after an action has been taken. It also fixes a bug where the net and CPU balances are swapped on the unstake tab. 
it also fixes a bug where some transactions would fail due to having a zero in an input. this bug was due to handling of `0.0000 TLOS` being truncated to `0 TLOS` which causes the tx to fail
it also fixes a bug where some txns would fail because large numbers were commified when they should not have been
- go to https://deploy-preview-663--obe-staging.netlify.app/
- sign in using anchor with an account which has various balances (staked to net, staked to cpu, savings, etc)
- go through all of the tabs in Send, Resources, and Staking (REX) sections of the account page. for each tab, try …
=> #507 | Auto refresh balances, misc bug fixes

src/components/AccountCard.vue, src/components/resources/ResourcesInfo.vue, src/components/resources/StakeTab.vue, src/components/resources/UnstakeTab.vue, src/store/antelope.store.ts, src/store/index.ts, src/store/resources/actions.ts, src/store/resources/getters.ts, src/store/resources/mutations.ts, src/store/resources/state.ts, test/jest/__tests__/store/antelope.store.spec.ts
@EJSG pointed out that after the transaction to undelegated resources was successfully executed, the account data didn't refresh automatically and indeed, that was happening. So I took the opportunity to fully incorporate the new `AntelopeStore` prototype into the two components related to the only part implemented for now in the new library. Those components are `StakeTab` and `UnstakeTab`.
This method sendTransaction:
https://github.com/telosnetwork/open-block-explorer/blob/master/src/components/resources/StakeTab.vue#L94-L132
Now looks like this, and the best part everything updates Automatically after the action call ends.
https://github.com/telosnetwork/open-block-explorer/blob/206e58c8b49ce3f7d5d8ea8d6709781efd1c1698/src/components/resources/StakeTab.vue#L93-L116
Also the Resource …
=> full incorporation of the new AntelopeStore.resource into StakeTab and UnstakeTab components

src/components/TransactionsTable.vue
This PR is a partial fix for flickering pagination. the issue is that the backend returns a different number of results for the same query at random (try going [here](https://testnet.telos.net/v2/history/get_actions?sort=desc&limit=10&account=eztestnet123) and reloading several times, see results vary). For now this PR hides the total number of pages when live transactions is enabled (live transactions = new query every few seconds = changing results because of bug). it also fixes the Last Page button to disable Live Transactions, and disables Live Transactions toggle when not on the first page
- go to https://deploy-preview-665--open-block-explorer.netlify.app/account/eztestnet123 and scroll to the transaction table
- disable live transactions
- click Last Page
- results should no longer …
=> #650 | Pagination flickering

src/components/resources/SellRam.vue, src/components/resources/StakeTab.vue, src/components/resources/UnstakeTab.vue, src/components/staking/SavingsTab.vue, src/components/staking/StakingTab.vue, src/components/staking/UnstakingTab.vue, src/components/validators/ValidatorData.vue, src/utils/string-utils.ts, test/jest/__tests__/utils/string-utils.spec.ts
- adjusts max input to be less than total matured
- refactor validation for input, and assetToAmount method
Unstake Max Amount:
1. navigate to staking resources page
2. select 'unstake' tab
3. see max input amount less than total matured
4. click max input to populate, and 'unstake' for successful tx
Input Validation
1. manually enter invalid amount
2. see input validation error on input
3. 'unstake' button does nothing
-   [ ] I have checked my code and corrected any …
=> 520 unable to withdraw the entire rex value

src/components/AccountSearch.vue, src/components/TransferAction.vue
The fields 'from' and 'to' values weren't been updated when manually typing the account name, only when clicking on an option on the list.
Updated the code to emit 'update' event when the new prop is true, the list has only one optio and the option matches the value on the input field.
Manually tested:
- Input letter by letter on the field and check if the proposal was properly created.
- Checked if filter on the transactions table wasn't affected by this change.
-   [x] I have removed any …
=> Fix for model not being updated on 'from' and 'to' fields.

src/components/AccountCard.vue
see issue description
1.  log in and navigate to 'wallet' page
2.  'Rex Profits' should not be in balance breakdown list
3.  Balance items should sum to total 
=> fix: remove rex profits from balance breakdown

src/components/contract/ContractActions.vue
Changed the name of one of the properties for `sendAction` from `action` to `name`. This makes the action **name** appear in the json file. 
-   [ ] I have included all english text to the translation file
-   [ ] I have created a new issue with the required translations for the currently supported languages
-   [ ] I have added appropriate test coverage
=> Includes action name when sending actions

.env.example, src/boot/ual.ts, src/components/ChainsMenu.vue, src/components/Header.vue, src/config/BaseChain.ts, src/config/ConfigManager.ts, src/config/chains/jungle/index.ts, src/config/chains/telos-testnet/index.ts, src/layouts/MainLayout.vue, src/types/Chain.d.ts
Improving the UX of multi chain functionality by moving it from the side menu to a menu button and included a tag on the chain logo to indicate when the User is under a testnet environment.
Also, fixed a bug regarding authentication where the system was keeping the account connected when changing the network.
- Selected a testnet chain and checked if the testnet tag appears.
- Changed from one chain to another and checked if the environment changes.
-   [X] I have removed any unnecessary …
=> Refactoring multichain sidemenu to a selector component

src/components/staking/SavingsTab.vue, src/utils/string-utils.ts, test/jest/__tests__/utils/string-utils.spec.ts
See issue description
See issue for testing steps
-   [x] I have added appropriate test coverage
=> unstake and savings available inputs displaying incorrect value

src/components/transaction/DataFormat.vue, src/components/transaction/PrettyPayload.vue
This PR fixes the issue where the content of an action is continuously appended to the table with the following changes:
1. Custom check to identify if the data is the same as received in the previous request
**Why?** The request answer _sometimes_ includes keys that are empty and sometimes it doesn't. The diff below illustrates the difference between the request payloads. Fun fact, they also change the order of the attributes, which is not depicted in the example below.
**How?** We recursively compare the each key since we can't predict the kind of data it will be. We ignore any key that has zero content in the comparison, so the objects are considered the same.
``` diff
{
"data": {
"permission": "active",
"parent": "owner",
"auth": {
"threshold": 2,
-
+              "keys": [], …
```
=> Fixes actions payload continuously appending 

src/components/staking/SavingsTab.vue
Minor bug fix to allow the user to put all (max available) amount to savings in REX.
- go to [this link ](https://deploy-preview-735--obe-testnet.netlify.app/)and login
- go to wallet / REX / savings
- press the max-available button (displaying how much you have on top of the input field)
- press the "Move to savings" button.
- It should work!
-   [x] I …
=> now we can move all to savings in rex

src/components/Footer.vue, src/config/chains/eos/index.ts, src/config/chains/jungle/index.ts, src/config/chains/telos-testnet/index.ts, src/config/chains/telos/index.ts, src/css/quasar.variables.sass, src/types/Theme.ts
Updating footer colors to keep consistency and creating a new variable for footer background.
-   [x] I have tested for mobile functionality and responsiveness
=> Updating footer colors

package.json, src/components/LoginHandler.vue, src/components/WorldMap.vue, src/config/BaseChain.ts, src/config/chains/eos/index.ts, src/config/chains/jungle/index.ts, src/config/chains/ux/index.ts, src/config/chains/wax/index.ts, src/pages/Network.vue, src/router/index.ts, src/store/account/actions.ts, test/jest/__tests__/store/account/actions.spec.ts
Turning off maps for other networks.
Manually tested if the map was removed from each network.
=> Turning off maps for other networks

src/components/AccountCard.vue
Fixing account not found when REX info are not available for some chains, such as Wax.
=> Fixing account not found when REX info are not available

src/components/transaction/DataFormat.vue
Increases the row height on the transaction table so the memo is visible:
before:
now:
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test …
=> Increases row height for memo to be visible

src/router/index.ts
The router wasn't taking into consideration the current chain for urls that come from the application itself, which don't have the network in the path. 
Current changes just make sure that if we have a current chain selected in the current session, we continue to use that before falling back to the preferred chain. 
Note that this would be a great candidate for a refactor, which will be addressed in future PR.
- …
=> Including local storage as fallback

src/components/TransactionsTable.vue, src/pages/TransactionPage.vue
This PR removes the live transactions toggle from a single transaction page. 
1. Go to any transaction page
2. See that the live transactions toggle is not visible anymore
-   [ ] I have tested for …
=> Removes live transactions from single transaction

src/components/LoginHandlerDropdown.vue
Simple text string fix of misspelling
Boot app, log in , and check 'Disconnect' button is spelled correctly.
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added …
=> Fix misspelling of 'Disconnect'

src/config/ConfigManager.ts, src/router/index.ts, src/router/routes.ts
Disabling landing page on single-chain mode.
Includes fix for validation of `SHOW_MULTICHAIN_SELECTOR` that is a `string` and was being considered a `boolean`.
- Make sure `SHOW_MULTICHAIN_SELECTOR` is `false`
- Make sure you have `CHAIN_NAME` set to the desired network
- Navigate through the website without ever seeing the home page
-   [ ] I have included …
=> Fixing landing page on single chain mode

src/components/transaction/DataFormat.vue
Adjusted height before "expand button" for tx payload to approximately three lines instead of 2.
Went to page, checked how many lines show the "expand" button vs does not show it.
=> Increase tx payload height to 3 lines (instead of 2)

src/components/AccountCard.vue
Max size takes precedence since it is arguably more important: used size is only relevant when a significant portion of max size. Logic ignores max size only for accounts that are privileged / system.
Checked values on accounts with NET or RAM that is:
a.) less than 1mb
b) less than 1gb but greater than 1mb
c.) greater than 1gb (eosio.evm)
d.) system account (eosio)
-   [X] I have tested for mobile functionality and responsiveness
=> Implement logic for showing gb vs mb vs kb for account resources

src/components/PriceChart.vue
It checks the price and if it is under 1 USD then it adds an extra decimal (3 instead of 2). Relevant for current TLOS price.
Checked on desktop and mobile
-   [X] I have tested for mobile …
=> Add decimal place for any token under 1 USD

src/components/AccountCard.vue
Adjusted the opacity from 0.5 to 0.8 for the account statistics area. I still think the readability is mediocre but that's a different discussion.
Tested in desktop browser. Mobile should not be any different.
Before:
After:
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the …
=> Adjust account statistics font color

src/components/transaction/DataFormat.vue
Styling adjustments for tx payload data that is either a.) too long for one line or b.) goes vertically past the "expand" icon (downward chevron / arrow)
Checked on both desktop and mobile
-   [X] I …
=> Hide tx data overflow and allow line-wrap

src/components/transaction/TransactionCard.vue
- TX timestamp showing incorrect because block timestamps do not have the 'Z' indicating the UTC time zone. They are not ISO-compliant 👎 but since they always do not have the 'Z' then we can just manually add it
Time now matches the timestamp on the homepage
-   [ ] I have included all english text to the translation file and/or created a new issue with the …
=> Add 'Z' to tx timestamps to tell client that it's UTC

src/components/LoginHandlerDropdown.vue
Changed the account dropdown from displaying the account name (again) to "Account". Also added some hover effects.
Checked on both desktop and mobile
-   [X] I have tested for mobile functionality …
=> Adjust Account dropdown text and background on hover

src/components/MapData.vue
Just added a couple of `.toLocaleString()` to the numbers
Just go to homepage and check it yourself.
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added …
=> Add comma separators for block numbers on homepage

src/pages/Error404.vue, src/router/routes.ts
- Made the 404 route page component fit within the `MainLayout` component to maintain consistent layout / style
-Checked on desktop and mobile
-   [X] I have tested for mobile functionality and …
=> Fix 404 error route

src/components/transaction/PrettyPayload.vue
If data key value is a flat array of non-objects, display array as data key value in transactions table
-   [x] I have tested for mobile functionality and responsiveness
=> Display flat array values in transactions table

src/components/BpVotes.vue, src/pages/Account.vue
Add a tab on the Account page that shows the BPs that the user has voted for.
Go to account page and click on "Votes" tab.
https://github.com/telosnetwork/open-block-explorer/assets/6249205/e93ffc06-3698-46ed-996c-7c22a334795b
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the …
=> Add BP Votes Tab to Account Page

src/config/chains/eos/index.ts, src/config/chains/jungle/index.ts, src/config/chains/ux/index.ts
Using the previous mainnet endpoint would show transactions until Dec 7th. Eos testnet was not loading with previous endpoint.
- Verify that transactions are updating to present date on EOS mainnet
- Verify that transactions are updating to present date on EOS testnet
- Verify all other chains still update their transactions
-   [ ] I have included all …
=> Eos endpoints

src/components/HeaderSearch.vue, src/pages/ProposalItem.vue, src/utils/sleep.ts, src/utils/string-utils.ts, src/utils/time.ts
Added a debounce utility function and implemented it for header search
Start typing into header
-   [X] Any dependent changes have been merged and published in downstream modules
-   [X] I have included all english text to the translation file and/or created a new issue with the required translations for the currently supported languages
-   [X] I have tested for mobile functionality and responsiveness
-   [X] I have added appropriate …
=> Debounce header search input

src/components/TransactionsTable.vue
Remove unnecessary console log
Used `localStorage` to set user's preference for how many txs per "page". If `localStorage` value is ever invalid it will replace it with a valid value (smallest option, currently `10`). URL query params take precedence over `localStorage` value
Go to homepage and start changing the items per page value. Removing params from URL and reloading should show saved setting # of transactions. Keeping query params in URL should have those params take precedence over user setting.
=> Implement localStorage saving of tx pagination batch size

src/components/ProposalUploadCSV.vue
see issue. `useStore()` was being called in an invalid scope within the csv upload component resulting in undefined store references.
see issue
=> CSV Upload

package.json, src/api/eosio_core.ts, src/components/AccountCard.vue, src/components/AccountSearch.vue, src/components/BpVotes.vue, src/components/ChildrenPanel.vue, src/components/HeaderSearch.vue, src/components/KeysPanel.vue, src/components/TokensPanel.vue, src/components/contract/ContractActions.vue, src/components/contract/ContractTables.vue, src/pages/Account.vue, src/store/account/actions.ts, src/store/resources/actions.ts, src/types/Actions.ts, src/utils/string-utils.ts, src/utils/systemAccount.ts, yarn.lock
Fix issue of "viewed" account not changing when URL changes
1. Go to an account and play around with the tabs
2. Go to a different account and view those tabs
3. Press browser's "back" button to get back to original account
4. Make sure that each account tab reflects the *current* account's information
-   [X] Any dependent changes have been merged and published in downstream modules
-   [X] I have included all english text to the …
=> 812 account tabs

src/pages/ProposalItem.vue
Allow any user to execute an approved proposal
Execute an approved proposal with an account that was not required to approve
=> fix: allow any user to execute an approved proposal

src/config/ConfigManager.ts, src/pages/ProposalItem.vue
This PR repairs the login behind the condition of isApproved. it also fixes a problem with the .env when it's not present (fresh repo clone).
- Go to this proposal link (I don't have a Mainnet deployment to show)
- Get logged in (use a non-BP account)
- See that it already shows an execution button
or run it locally with this code:
```bash
git clone https://github.com/telosnetwork/open-block-explorer.git
cd open-block-explorer
git fetch origin
git checkout 835-execute-msig-tx-by-non-msig-accounts-on-block-explorer
yarn
yarn dev
```
make sure you have the file `.env` with this code:
```
APP_NAME=OBE
CHAIN_NAME=telos
```
then visit http://localhost:8080/proposal/aprfeeburn
-   [x] I have commented my code, particularly in …
=> Fix proposal execute button - fixing the math for isApproved

quasar.conf.js, src/boot/fathom.ts, src/config/BaseChain.ts, src/config/chains/eos/index.ts, src/config/chains/jungle/index.ts, src/config/chains/telos-testnet/index.ts, src/config/chains/telos/index.ts, src/config/chains/ux/index.ts, src/config/chains/wax/index.ts, src/types/Chain.d.ts
This PR adds the Fathom analytics library to track traffic without specific events. Each chain may or may not have a SiteId already set to be used for the library.
=> #839 | adding fathom analytics

src/components/SendDialog.vue, src/config/chains/wax/index.ts
Updates WAX's precision from 4 to 8 so users don't have to manually change it. It also removes the one instance found that used a hardcoded precision and not the one defined within the chain configuration file.
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for the currently …
=> Updates WAX precision

src/components/BlockCard.vue, src/components/TransactionsTable.vue, src/pages/Block.vue
Paginates transaction table by actions, since each row is an action that references a transaction, we will show 10 or whatever number selected of rows per page instead of all actions for a single transaction.
Verify that block pages are paginating accurately, try blocks around :1289 and newer blocks as well as any blocks you might have knowledge of being special in any way.
Verify filters are working at least as well as in the production release, create a separate issue for any issues found here that are also present in release.
-   [ ] Any dependent …
=> Paginate by action
