telosnetwork/open-block-explorer

src/components/Header.vue
src/router/index.ts

- temp workaround for router.push()

fix(temp): nav to routes on router push

---

src/components/Header.vue
src/components/TransactionsTable.vue

- checks if tx id exists before pushing to router
- indicate bad tx id with toast and prevent navigation to bad route

fix: check if tx id exists

---

src/components/Footer.vue
src/components/Header.vue
src/components/TransactionsTable.vue
src/css/app.sass
src/pages/Privacy.vue
src/pages/Terms.vue
src/router/routes.ts

- hide connect button
- hide table filter buttons
- hide pagination if one or less page of results
- legal, privacy, repo  links updated in footer
- remove unused routes & placeholder components for 'terms' , 'privacy'

Bugfix/hide unimplemented UI

---

src/pages/Account.vue
src/pages/Block.vue
src/pages/Network.vue
src/pages/Transaction.vue

fix: reduce gradient box height

---

src/components/PriceChart.vue

fix: format 24hr change value as percentage

---

src/components/AccountCard.vue
src/components/Header.vue
src/components/PercentCircle.vue
src/components/PriceChart.vue
src/css/app.sass
src/css/quasar.variables.sass
src/layouts/MainLayout.vue
src/pages/Account.vue
test/jest/__tests__/components/Header.spec.ts
test/jest/__tests__/components/PercentCircle.spec.ts
test/jest/__tests__/components/TransactionsTable.spec.ts

- re-design implemented to adjust fonts, remove card-style background, etc
- add animated circle graphs to display resource data
- add total usd value for total TLOS amount

72 wallet   single account template updates - main informational section

---

package.json
src/components/DateField.vue
src/components/TransactionsTable.vue
yarn.lock

- add expand/collapse functionality to table data column, toggle via chevron button, one row at a time, w/animation #55* 
- add 'voter' and 'account_name' (variation of 'account') data variables to regex to render as links to account page
- fix overlapping columns & values (mobile) #81 
- newline prepended to row data column removed 
- force line break for overflowing column data
- format timestamp (to  match Etherscan & Teloscan) formatting #83 
*Note: re #55 the tx set grouping part of the feature request needs it's own card and is not included in this PR.

table features & bugs - #81, #83, #55 

---

quasar.conf.js

Fixes routing issue for local dev environment see #94

94 bug routes with periods fail in local dev environment

---

jest.config.js

- add thresholds in jest config

feat: add thresholds for layouts & pages

---

src/components/AccountCard.vue

106 ram usage is incorrect

---

src/components/AccountCard.vue
src/components/SendDialog.vue
src/css/app.sass

Fixes #122 #117 #115 #114 #113

115 bug pr possible to add negative amount on transfer before signing

---

src/components/CoinSelectorDialog.vue

suppress empty token positions
Fixes #116 

116 enhancement pr suppress empty token positions

---

src/components/Header.vue

Type ahead will now start searching when only one option is available

feat: Type ahead execute search on one value

---

src/components/ProposalSuccess.vue
src/components/ProposalTable.vue
src/composables/useAuthenticator.ts
src/pages/Proposal.vue
src/pages/ProposalNew.vue
src/router/routes.ts
src/types/Actions.ts
src/types/Proposal.ts
src/types/index.ts
src/utils/apiEos.ts
src/utils/deserializeActionData.ts
src/utils/handleEosioName.ts
src/utils/serializeActionData.ts

This PR adds the ability to create a new multi-signature proposal from the interface through a form.
It also fi
Fixes #163 
Manual tests.

163 new msig

---

src/components/Map.vue

Made the map overlays a bit more compact with 70% opacity. Added a local storage entry to disable the overlays.
Fixes #178

178 feature request improve design of bp labels on map

---

src/components/AccountCard.vue
src/components/MapData.vue
src/components/PriceChart.vue
src/css/app.sass

Fixed some inconsistant fonts added the Actor font-family in a coupe of places according to the designs.
Fixes #119

119 enhancement pr 109 typography fonts use same font

---

src/components/Header.vue
src/pages/ProposalItem.vue
src/pages/ProposalNew.vue
src/router/routes.ts

- Makes the authorization field mandatory in the m-sig form
- Includes the page where you can see the details of a single multi-signature proposal
- Allows users to execute, cancel and approve the proposal
Fixes #164 

[Closes #164] Execute multi-signature proposal

---

src/components/TransactionsTable.vue

added watcher for account name in TransactionTable component, which is updated asynchronously on init account page load
Fixes #194

194 bug transactions do not display on account page initial load

---

package.json

- update page title
- update version number (missed prev)

fix: update page title (tab)

---

src/components/validators/ValidatorData.vue
src/components/validators/ValidatorDataTable.vue
src/css/app.sass
src/store/account/actions.ts
src/store/chain/actions.ts
src/store/chain/mutations.ts
src/store/chain/state.ts
src/types/Producers.ts
src/types/index.ts

Producer data comes from table request and gets padded with bucket BP.json data if available. Needed this because if the bucket does not update the order of the list is inacurate.

fix: BP list from chain

---

src/api/hyperion.ts
src/pages/ProposalItem.vue
src/types/Proposal.ts
src/types/index.ts

This PR addresses bugs that were identified on the proposal page. 
- The transaction section shows the information related to the msig creation action
- The action buttons in the banner show according to the user logged in and the status of the msig
- Banner size has been reduced
- Banner shows status of the msig for users that don't have permission to execute any action
- Transaction history is displayed at the end of the page
These fixes depend on the `onMouted`, which is why we're opening a PR with all of them.
Fixes #225, #224 

[Fixes #224, #225] Transaction information and banner issues 

---

src/utils/apiEos.ts

This PR changes the logic to get the user identifier so it will work on all environments
Fixes #231 

fix: get anchor link identifier of localStorage

---

src/components/ProposalAction.vue
src/components/ProposalAuthorization.vue
src/pages/ProposalNew.vue
src/types/Proposal.ts

Taking advantage of the account search that has been added for permissions, we also look for the actions within one that has a smart contract.
This enables the msig not only to be generalized and shows all possible actions and the necessary inputs for each of them.
Fixes #234 

234 msig actions

---

src/pages/Transaction.vue
src/store/transaction/actions.ts
src/store/transaction/mutations.ts
src/store/transaction/state.ts

Show transaction not found card instead of empty transaction details.
Fixes #268 
* Hardware:
* Toolchain:
* SDK:

268 feature request transaction not found

---

src/pages/ProposalItem.vue

- Adds unapprove button action
- Execute available for all accounts in the approvals list
- Cancel available only for the proposer
- Shows a single tag. `executed` from the proposal json is marked as `true`, even after the cancellation. The cancel is showed only as the last action in the msig.
Fixes #261 and #264

fix: add unapprove button and show one tag only

---

package.json
quasar.conf.js
src/boot/ual.ts
src/components/LoginHandler.vue
src/components/LoginHandlerDropdown.vue
src/components/Rex/RexDialog.vue
src/components/Rex/StakedTab.vue
src/components/SendDialog.vue
src/components/Staking/RefundTab.vue
src/components/Staking/StakeTab.vue
src/components/Staking/UnstakeTab.vue
src/store/account/actions.ts
src/store/account/getters.ts
src/store/account/mutations.ts
src/store/account/state.ts
src/types/vue-global.d.ts
yarn.lock

Fixed signing flow and double login issues with signer. Also added cleos signer support.
Fixes #218 
* Hardware:
* Toolchain:
* SDK:

218 bug sign transaction ux

---

src/api/eosio_core.ts
src/pages/ProposalItem.vue
src/types/Actions.ts

Example using `@greymass/eosio` classes to achieve the same results. Feel free to reject this PR, was more an experiment to see how I'd accomplish the same thing.

Alternative using core classes

---

src/components/Rex/HistoryTab.vue
src/components/validators/ValidatorData.vue
src/layouts/MainLayout.vue

Some issues I noticed while doing a sanity check.
Fixes # (issue)
* Hardware:
* Toolchain:
* SDK:

fix: some issues noticed

---

src/components/KeyAccountsCard.vue
src/components/KeyToggle.vue
src/components/PermissionCard.vue

Added public key toggle to the keys tabs. Keys also link out to the keys page.
Fixes #191
* Hardware:
* Toolchain:
* SDK:

191 feature request pub key toggle

---

src/components/contract/Actions.vue
src/store/account/actions.ts
src/store/account/mutations.ts
src/store/account/state.ts

Fixes #296 
* Hardware:
* Toolchain:
* SDK:

fix: contract actor and permission defaults

---

src/router/index.ts

Route changes do not affect page position anymore. Removed the scroll behaviour from the router.
Fixes #295
* Hardware:
* Toolchain:
* SDK:

fix: removed scroll behaviour

---

src/components/LoginHandlerDropdown.vue
src/components/WalletModal.vue
src/css/app.sass
src/css/quasar.variables.sass

Account dropdown link to account page. Removed navigation on login. Added disconnect all and attach an account.
Fixes #298
Fixes #136 
* Hardware:
* Toolchain:
* SDK:

feat: account link in navbar

---

src/components/Map.vue

Disabled the zoom on map, scrolling on the map will scroll the page.
Fixes #313 
* Hardware:
* Toolchain:
* SDK:

fix: disable map zoom and interactions

---

src/components/LoginHandlerDropdown.vue
src/components/WalletModal.vue
src/components/validators/ValidatorData.vue

Anchor does not popup after a disconnect and a reconnect fixed. Also removed "disconnect all" and "attach account" buttons from account dropdown.
* Hardware:
* Toolchain:
* SDK:

fix: disconnect and removed buttons

---

src/components/Resources/ResourcesDialog.vue

Moved the refund CPU/NET tab next to the other CPU/NET tabs.
Fixes #328 
* Hardware:
* Toolchain:
* SDK:

Move and rename refund tab.

---

src/components/Resources/ResourcesDialog.vue
src/components/Staking/StakingDialog.vue

Fixed vertical centering on dialogs with tabs to avoid content shifting when auto centering.
Fixes #334 
* Hardware:
* Toolchain:
* SDK:

fix: center vertically removed for dialogs

---

src/pages/ProposalItem.vue

document refresh on proposal action immediately dismisses cleos popup, need to implement proposal refresh in a different way.

fix: automatic doc reload is dismissing cleos popup

---

src/components/ProposalAction.vue

This fix automatically fills the empty memo so the user doesn't need to focus/click on the input to me saved as `null`.
Fixes #338 

fix: Optional memo

---

src/components/SendDialog.vue
src/components/Staking/SavingsTab.vue
src/components/Staking/StakeFromNetCpuTab.vue
src/components/Staking/StakingTab.vue
src/components/Staking/UnstakingTab.vue

Allow users to select max amounts where relavant for input values by clicking on the balance.
Fixes #300 
* Hardware:
* Toolchain:
* SDK:

feat: max amount option on inputs

---

src/boot/ual.ts

Missing quote on the cleos transaction popup.
* Hardware:
* Toolchain:
* SDK:

fix: cleos missing quote

---

src/components/AccountCard.vue
src/components/Resources/ResourcesInfo.vue
src/components/Resources/StakeTab.vue
src/store/account/actions.ts
src/types/Actions.ts

Fixed total staked value on account page.
* Hardware:
* Toolchain:
* SDK:

fix: core rex balance

---

src/components/SendDialog.vue

Fixed the default input behaviour for the send modal. The other modal inputs have already been fixed in a similar way in a previous PR.
Fixes #352 
* Hardware:
* Toolchain:
* SDK:

fix: default input for send modal

---

src/components/AccountCard.vue
src/components/Staking/StakingDialog.vue
src/store/account/actions.ts
src/store/account/mutations.ts
src/store/account/state.ts

Funds that get stuck in rexfund can now be removed with a the withdraw button.
Fixes #364 
* Hardware:
* Toolchain:
* SDK:

364 feature request widraw button for fund

---

src/components/AccountCard.vue

Fixes the issue of seeing random balances when viewing non existing accounts. Also now shows account not found instead of empty values.

fix: account page showing wrong balances for non existing accounts

---

package.json
yarn.lock

chore: bump ual-cleos version

---

.env.example
netlify.toml
src/config/chains/eos/index.ts
src/config/chains/jungle/index.ts
src/config/chains/telos-testnet/index.ts
src/config/chains/telos/index.ts
src/config/chains/ux/index.ts
src/config/chains/wax/index.ts

fix api url to use https
- APY value should display on account REX page

fix: api url to use https

---

src/components/TransactionsTable.vue

422 improve show age toggle label

---

src/components/Resources/RefundTab.vue
src/components/Resources/ResourcesDialog.vue
src/components/Resources/ResourcesInfo.vue
src/components/Transaction/DataFormat.vue

417 resource page with 2 decimal numbers

---

src/components/HeaderSearch.vue

Reducing the debounce resulted in race conditions that returned multiple sets of results. refactored to set results synchronously after all async queries are resolved.  
should return filtered results on input

432 cumulative search results on debounce

---

src/components/ProposalAuthorization.vue
src/components/ProposalUploadCSV.vue

This PR changes any uppercase account to lower case
It also parses to verify the validity of accounts
- manual tests with account uppercase on the csv file
- manual tests with invalid accounts 

feat: convert all letters into lowercase

---

jest.config.js
src/components/HeaderSearch.vue
src/components/LoginHandlerDropdown.vue
src/components/ProposalAuthorization.vue
test/jest/__tests__/components/PercentCircle.spec.ts

Resolves template compilation errors when collecting test coverage, and #444 

test: resolve failed coverage errrors

---

src/components/DateField.vue

Fixed transaction format to 24hours

fiX: format of transaction dates

---

src/components/TransactionsTable.vue

hotfix: invalid date

---

src/components/Staking/StakeFromResources.vue

hotfix: stake from cpu/net

---

src/components/Resources/RefundTab.vue

hotfix: refund cpu/net tab form

---

src/components/Resources/ResourcesInfo.vue

hotfix: fix NaN display for refunding when no refund in progress

---

package.json
src/components/AccountCard.vue
yarn.lock

hotfix: system account not found

---

package.json
src/components/AccountCard.vue
src/components/validators/ValidatorData.vue
yarn.lock

1. log in and navigate to explorer.telos.net/vote
2. see language update and verify value matches that found in the voters table (view contract for 'eosio' account to verify)
3. see tooltip explaining vote weighting
4. change vote, on successful tx, see vote weight update

511 incorrect voting tlos balance

---

LICENSE.md
README.md

- Adds license to project by using license template from GitHub
- Adds license badge to readme file

Adds Apache License

---

src/components/AccountCard.vue
src/components/validators/ValidatorData.vue

521 staking dialog balances

---

.env.example
src/layouts/MainLayout.vue

Update env.example, remove unused env vars, point to `src/config`
- toggle between main and test net by changing `CHAIN_NAME` env var
-   [x] I have created a new issue with the required translations for the currently supported languages

docs: update .env.example remove unused vars

---

src/components/Transaction/DataFormat.vue
src/components/TransactionsTable.vue

This PR fixes most of the requests made in issue #546. 
- Pagination: a text saying "page N" was added next to the navigation footer buttons. Also, the pagination now is driven by the URL page param.
- The transfer undefined data problem was solved by replacing a once-precalculated variable with a computed always-updated one.
- Layout: The repeated title was removed and the time relative switcher was repositioned next to the header filter buttons.
- 'See More' button: The variable used to include the switcher was calculated only once and therefore always out-dated. It was replaced with a computed variable.
- go to [this account page](https://deploy-preview-561--obe-staging.netlify.app/account/montevideouy)
- You should see a screen like the one on the screenshot (take a look at the …

fix: transactions table component enhanced (url pagination, undefined data, layout, see more button)

---

src/components/Resources/BuyRam.vue
src/components/Resources/SellRam.vue
src/components/Resources/StakeTab.vue
src/components/Resources/UnstakeTab.vue

This PR makes improvements to the inputs within the Resources section of the app. In particular, it:
1. adds a total available balance indication for each input, to match those in the Staking section of the app (the total is clickable to allow the user to auto-fill the maximum amount for each input)
2. improves error messaging 
- go to https://deploy-preview-580--obe-testnet.netlify.app/
- log into an account with some balances, e.g. cleos - `eztestnet123`
- go to the account page for the account, e.g .https://deploy-preview-580--obe-testnet.netlify.app/account/eztestnet123
- click Resources
- do the following for each tab: Add CPU/Net, Remove CPU/NET, Buy RAM, Sell RAM
- verify that while the input value is 0, the Confirm button is disabled
- each input should show the total available …

#545 | Resources inputs enhancements

---

.github/workflows/main.yml
src/components/Resources/UnstakeTab.vue

1. navigate to Account -> Resources -> 'Remove CPU/NET' tab
2. enter value for either CPU or NET (leave other empty) 
3. transaction should succeed 
-   [x] I have created a new issue with the required translations for the currently supported languages

597 cant remove cpunet

---

src/components/TransactionsTable.vue

1. input any combination of from/to for the date filter on transactions page
2. see table filtering and no errors in console
-   [x] I have created a new issue with the required translations for the currently supported languages

Filtering by date breaks pagination

---

src/components/AccountCard.vue

This PR adds a loading state for Resources and Staking buttons on the account view
- go to https://deploy-preview-632--obe-testnet.netlify.app/
- log in
- go to your account page
- while the page is loading, all the buttons should be disabled and say "Loading"
-   [x] I have created a new …

#630 | Resources loading error

---

src/components/TransactionsTable.vue
src/pages/Block.vue
src/pages/Transaction.vue

-   [x] I have created a new issue with the required translations for the currently supported languages

638 remove live tx and table filters from pages where they dont apply

---

src/components/TransactionsTable.vue
src/pages/Account.vue

This PR adds pagination functionality to the transaction table
- go to homepage https://deploy-preview-648--obe-testnet.netlify.app/
- there should be no row count at the top of the table
- there should be no 'last' button at the bottom of the table
- there should be no total page count, only current page indicator (e.g. 'page 2')
- go to an account with one page of transactions https://deploy-preview-648--obe-testnet.netlify.app/account/eztestnet111
- all buttons should be disabled
- row count at the top should be accurate
- page count at the bottom should say page 1 of 1 
- go to an account with several pages of transactions  https://deploy-preview-648--obe-testnet.netlify.app/account/eztestnet123     
- until you change page, only next and last buttons should be enabled
- row count at …

#392, #645 | Transaction table 

---

src/components/SendDialog.vue
src/css/app.sass
src/store/account/actions.ts

This PR updates the UI for successful token send state and fixes the inability to send tokens. eslint warnings are fixed in another PR, ignore them
- go to https://deploy-preview-656--open-block-explorer.netlify.app/
- sign into an account with nonzero liquid balance using anchor
- go to your account page
- click `Send`
- try to send some TLOS to another account
- sending should work
- the success state should match the acceptance criteria 
-   [x] I have checked my code …

#596, #653 | Send token fixes

---

src/components/HeaderSearch.vue

- see #635 
- note: not specific to testnet

fix: restore missing class for search select

---

src/config/chains/jungle/index.ts
src/config/chains/telos-testnet/index.ts
src/config/chains/telos/index.ts

fix: update endpoints

---

jest.config.js
src/App.vue
src/boot/ual.ts
src/components/ChainsMenu.vue
src/components/Header.vue
src/components/LoginHandler.vue
src/components/LoginHandlerDropdown.vue
src/components/resources/BuyRam.vue
src/components/resources/RefundTab.vue
src/components/resources/SellRam.vue
src/components/resources/StakeTab.vue
src/components/resources/UnstakeTab.vue
src/components/staking/SavingsTab.vue
src/components/staking/StakeFromResources.vue
src/components/staking/StakingTab.vue
src/components/staking/UnstakingTab.vue
src/config/BaseChain.ts
src/config/ConfigManager.ts
src/config/chains/jungle/index.ts
src/layouts/MainLayout.vue
src/router/index.ts
src/store/account/actions.ts
src/store/account/mutations.ts
src/store/account/state.ts
test/jest/__tests__/store/account/actions.spec.ts
yarn.lock

Include network on route.
- Included a 'beforeRoute' on router to watch the param and change the system accordingly to the network on the URL
- Included a reactive state for route data to be able to listen URL changes
- Watching route data on MainLayout to live update Theme without the necessity of reload all application
- Creating some IDs for local storage variables resolved the issue to have more than one chain opened in the same browser. Fixes #705. Fixes #720.
- Tested changing network using MultiChain component;
- Tested changing network on URL;
- Tested getting a link form another network; …

Including URL on route

---

package.json
src/components/ProposalUploadCSV.vue
src/pages/ProposalItem.vue
src/pages/ProposalNew.vue
src/store/resources/actions.ts

hotfix: replace hard-coded active permission store reference

---

src/components/AccountCard.vue
src/components/Footer.vue
src/components/Header.vue
src/config/BaseChain.ts
src/pages/Account.vue
src/types/Chain.d.ts
src/types/UiCustomization.ts

This PR includes feature flags around the header functionalities, so any chain can choose more easily what features they want to provide.
The changes on this PR should not cause any behavioral change on any of the current chains. 
-   [ ] I have included all english text to the translation file and/or created a new issue with the required translations for …

Account header flags

---

src/components/AccountCard.vue

Total should update to include resources delegated to others

fix: uinclude resources delegated to others in total balance

---

src/components/Footer.vue
src/config/BaseChain.ts
src/config/chains/eos/index.ts
src/config/chains/jungle/index.ts
src/config/chains/telos-testnet/index.ts
src/config/chains/telos/index.ts
src/config/chains/ux/index.ts
src/config/chains/wax/index.ts
src/types/Chain.d.ts
src/types/UiCustomization.ts

Changed `BaseChain.ts` to allow chain-specific footer links
Enabled multichain selector and checked different chains. Links appear to be working correctly.
-   [X] I have tested for mobile …

Implement chain-specific footer links

---

README.md
test/jest/__tests__/store/account/actions.spec.ts

fix some comments
-   [ ] I have tested for mobile functionality and responsiveness
-   [ ] I have added appropriate test coverage
-   [x] I have updated relevant documentation and/or opened a …

chore: fix some comments

---

src/components/BlockTransactionsTable.vue
src/pages/Block.vue
src/pages/TransactionPage.vue

This Pr creates different Transaction table components for the Home and Block pages as requested in the issue

(Hotfix) separated transaction table components for home and block pages

---

package.json
yarn.lock

- Updates wharfkit sessions dependency and cleos plugin dependency to the newest versions which fix the issue.

update wharfkit sessions and cleos plugin
